### ISSUE TITLE
No fields in globalize action form

### ISSUE THREAD

**Issue by scarfacedeb** [andreazaupa/rails_admin_globalize#5]
Translated fields don't show up in globalize action's form.
Moreover, I don't understand why they should, given this code from globalize.html.haml:

``` ruby
rails_admin_fields = @object.class.rails_admin.edit.with(:view=>self, :object=>@object, :controller=>@controller).visible_fields.inject({}) { |a,f| a[f.name] = f if translations_field.include?(f.name) ; a }
```

I think, the problem is that `visible_fields` method doesn't return translated fields, because this's how it should work.
The backtrace for visible_fields call is:
`visible_fields` -> `RailsAdmin::Config::Fields.factory` -> `parent.abstract_model.properties` -> `RailsAdmin::Adapters::ActiveRecord.properties` -> `model.columns`

so, in the `RailsAdmin::Adapters::ActiveRecord.properties` method, properties array is created from `model.columns`, that returns only the columns from the current model.

That's why there's no translated fields in globalize form.

---

My question is - How did you managed to get translated fields in that form?
What's the trick? :)

**Comment by andreazaupa** [comment]
sorry, rails_admin_globalize is only a fast hack. 
I do not have time to maintain It properly. 
anyway, visible_fields methods should return the translated field if you explicitly include it in rails_admin configuration edit block  ... 

a.e for a translated field "title" of model Article 

``` ruby
config.model Article do
  edit do
    field :title
    # ... other fileds configuration or include_all_fields
  end
end
```

have a nice day

**Comment by scarfacedeb** [comment]
Thank you for an answer, but I actually created my own rails_admin plugin that is suited to my use case.
https://github.com/scarfaceDeb/rails_admin_globalize_field
